spring:
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: validate
  datasource:
    schema: classpath:/data/hsqldb/schema.sql
    data: classpath:/data/hsqldb/data.sql

management:
  security:
    enabled: false

endpoints:
  sensitive: false

---

spring:
  profiles: stage

server:
  port: 8090

---

spring:
  profiles: prod

server:
  port: 9000